[package]
name = "ggpk"
version = "0.1.0"
authors = ["Daniel Dimovski <daniel.k.dimovski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
byteorder = "1.3.2"
base64 = "0.11.0"
rayon = "1.3.0"