[package]
name = "ggpk"
version = "1.1.0"
authors = ["Daniel Dimovski <daniel@dicode.se>"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
byteorder = "1.3.4"
log = "0.4.11"
simplelog = "0.8.0"
clap = "2.33.3"
rayon = "1.5.0"
regex = "1"
widestring = "0.4.3"
